filePath=/Users/Dhruv.Desai/source/Student/boca-bc24-java-core-problems/src/problems/bnym-rule-set/src/main/resources/file/bony_cbna_ruleset_d100614.data

db.driver.class=com.mysql.cj.jdbc.Driver
hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.hbm2ddl.auto=update

dbUrl=jdbc:mysql://localhost:3306/bootcamp
dbUsername=root
dbPassword=password123